server:
  port: 8081  
  error:
    path: /error2

spring:  application:
    name: Bootstrap Spring Boot
  jpa:
    hibernate:      ddl-auto: none
      use-new-id-generator-mappings: false
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db-spring
    username: root
    password: nasser
    initialization-mode: always
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html 
