spring:
  profiles:
    active : dev  application:
    name: Bootstrap Spring Boot
  jpa:
    hibernate:      ddl-auto: none
      use-new-id-generator-mappings: false
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        id:
          new_generator_mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/spring?createDatabaseIfNotExist=true
    username: root
    password: nasser
    initialization-mode: always
    continue-on-error: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html 
  mail:
      host: smtp.gmail.com
      port: 587
      username: marwanayman1998@gmail.com
      password:  evkqolavxbevygrx
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
    
---
 spring:
    profiles: test
    h2:
      console:
        enabled: true
    application:
      name: Bootstrap Spring Boot
    main:
     allow-bean-definition-overriding: true
    thymeleaf:
      cache: false
      enabled: true
      prefix: classpath:/templates/
      suffix: .html

    datasource:
      continue-on-error: true
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
      username: mn
      password: mn
      driver-class-name: org.h2.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create